CREATE ROLE visiteur;

GRANT SELECT ON JEU TO visiteur;
GRANT SELECT ON EDITEUR TO vendeur;

CREATE ROLE vendeur;

GRANT visiteur TO vendeur;

GRANT SELECT ON INSTANCE_JEU TO vendeur;
GRANT SELECT ON ACHAT TO vendeur;
GRANT SELECT ON PLATEFORME TO vendeur;
GRANT SELECT ON EDITEUR TO vendeur;

GRANT INSERT ON ACHAT TO vendeur;
GRANT DELETE ON ACHAT TO vendeur;
GRANT UPDATE ON ACHAT TO vendeur;

CREATE ROLE catalogueur;

GRANT INSERT ON JEU TO catalogueur;
GRANT INSERT ON INSTANCE_JEU TO catalogueur;
GRANT INSERT ON PLATEFORME TO catalogueur;
GRANT INSERT ON EDITEUR TO catalogueur;
GRANT INSERT ON PLATEFORME TO catalogueur;

GRANT DELETE ON JEU TO catalogueur;
GRANT DELETE ON INSTANCE_JEU TO catalogueur;
GRANT DELETE ON PLATEFORME TO catalogueur;
GRANT DELETE ON EDITEUR TO catalogueur;
GRANT DELETE ON PLATEFORME TO catalogueur;

GRANT UPDATE ON JEU TO catalogueur;
GRANT UPDATE ON INSTANCE_JEU TO catalogueur;
GRANT UPDATE ON PLATEFORME TO catalogueur;
GRANT UPDATE ON EDITEUR TO catalogueur;
GRANT UPDATE ON PLATEFORME TO catalogueur;

CREATE ROLE administrateur;

GRANT ANY PRIVILEGE TO administrateur WITH ADMIN OPTION;